spring:
  datasource:
    driver-class-name:


jwt:
  header: Authorization
  secretKey : leebeomjunleebeomjunleebeomjunleebeomjunleebeomjunleebeomjun
  #1h
  accessToken-valid-seconds : 600
  #24h
  refreshToken-valid-seconds : 86400