spring:
  profiles:
    active: real

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/tableOrder;
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  header: Authorization
  secretKey : leebeomjunleebeomjunleebeomjunleebeomjunleebeomjunleebeomjun
  #3h
  accessToken-valid-seconds : 10800
  #24h
  refreshToken-valid-seconds : 86400

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: real

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://ec2-13-124-45-246.ap-northeast-2.compute.amazonaws.com/mysql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  header: Authorization
  secretKey : leebeomjunleebeomjunleebeomjunleebeomjunleebeomjunleebeomjun
  #3h
  accessToken-valid-seconds : 10800
  #24h
  refreshToken-valid-seconds : 86400




