spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/tableOrder;
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  header: Authorization
  secretKey : leebeomjunleebeomjunleebeomjunleebeomjunleebeomjunleebeomjun
  #3h
  accessToken-valid-seconds : 10800
  #24h
  refreshToken-valid-seconds : 86400

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod




